//! Schema migrations, compatible with the Go client and the CLI
//! (golang-migrate): the same version table, advisory lock and dirty-flag
//! protocol, so any client can migrate a database another one installed.

use sqlx::{AssertSqlSafe, Connection as _, PgConnection, PgPool};
use tracing::Instrument as _;

use crate::error::{Error, Result};

/// An embedded up migration.
struct Migration {
    version: u64,
    sql: &'static str,
}

// MIGRATIONS (and MQ_SCHEMA for tests): migrations 1..N of the pinned mq
// schema version, generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

/// The latest embedded migration.
const LATEST_VERSION: u64 = MIGRATIONS[MIGRATIONS.len() - 1].version;

/// golang-migrate's salt for advisory lock keys.
const LOCK_SALT: u32 = 1_486_364_155;

/// The migration state of a database, from [`migration_status`].
///
/// Not constructible outside the crate (fields may be added):
///
/// ```compile_fail,E0639
/// let _ = postgremq::MigrationStatus { ..unimplemented!() };
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub struct MigrationStatus {
    /// The applied version; `0` when no migration has been applied.
    pub current_version: u64,
    /// Whether the migration of `current_version` has not finished: it
    /// failed partway, or another process is applying it right now (the
    /// status is read without the migration lock).
    pub dirty: bool,
    /// The latest migration embedded in this crate.
    pub latest_version: u64,
    /// Whether `current_version` is below `latest_version`. A dirty database
    /// may report `false`; [`migrate`] refuses it either way.
    pub needs_migration: bool,
}

/// Applies the embedded migrations the database has not applied yet, up to
/// the latest embedded version.
///
/// A database already at a newer version (migrated by a newer client) is
/// left unchanged. Concurrent callers, in any client, are serialised by an
/// advisory lock. This is schema management, separate from
/// [`Connection`](crate::Connection): run it once before connecting, e.g. at
/// application start-up.
///
/// # Cancellation
///
/// Waiting for the lock (which has no time limit) can be cancelled: dropping
/// the future ends that session. Once migrations start applying, they run to
/// completion in a spawned task even if the future is dropped, so a cancelled
/// call never leaves a migration half-recorded.
///
/// # Errors
///
/// [`Error::DirtySchema`] when a previous migration failed partway;
/// [`Error::Sqlx`] for database errors, including a failing migration (whose
/// version is then left dirty).
pub async fn migrate(pool: &PgPool) -> Result<()> {
    run(pool, MIGRATIONS).await
}

/// Reads the migration state. Read-only: it works before the schema is
/// installed and needs no `CREATE` privilege.
///
/// # Errors
///
/// [`Error::Sqlx`] for database errors.
pub async fn migration_status(pool: &PgPool) -> Result<MigrationStatus> {
    let installed: bool =
        sqlx::query_scalar("SELECT to_regclass('postgremq.postgremq_migrations') IS NOT NULL")
            .fetch_one(pool)
            .await
            .map_err(Error::Sqlx)?;
    let (current_version, dirty) = if installed {
        read_version(&mut *pool.acquire().await.map_err(Error::Sqlx)?).await?
    } else {
        (0, false)
    };
    Ok(MigrationStatus {
        current_version,
        dirty,
        latest_version: LATEST_VERSION,
        needs_migration: current_version < LATEST_VERSION,
    })
}

async fn run(pool: &PgPool, migrations: &'static [Migration]) -> Result<()> {
    // Detached: the session holds a session-level advisory lock, so it must
    // never go back to the pool. Dropping it ends the session and the lock.
    let mut conn = pool.acquire().await.map_err(Error::Sqlx)?.detach();
    let lock = match lock(&mut conn).await {
        Ok(lock) => lock,
        Err(err) => {
            finish(conn, None).await;
            return Err(err);
        }
    };
    let current = match applied_version(&mut conn).await {
        Ok(current) => current,
        Err(err) => {
            finish(conn, Some(lock)).await;
            return Err(err);
        }
    };
    let task = tokio::spawn(
        async move {
            let result = apply(&mut conn, migrations, current).await;
            finish(conn, Some(lock)).await;
            result
        }
        .in_current_span(),
    );
    match task.await {
        Ok(result) => result,
        Err(err) if err.is_panic() => std::panic::resume_unwind(err.into_panic()),
        // The runtime is shutting down.
        Err(_) => Err(Error::Sqlx(sqlx::Error::WorkerCrashed)),
    }
}

/// Takes the migration lock; returns its key. Safe to cancel.
async fn lock(conn: &mut PgConnection) -> Result<i64> {
    let database: String = sqlx::query_scalar("SELECT current_database()")
        .fetch_one(&mut *conn)
        .await
        .map_err(Error::Sqlx)?;
    let lock = i64::from(lock_id(&database));
    sqlx::query("SELECT pg_advisory_lock($1)")
        .bind(lock)
        .execute(&mut *conn)
        .await
        .map_err(Error::Sqlx)?;
    Ok(lock)
}

/// Under the lock: creates the version table if needed and returns the
/// applied version, refusing a dirty one. Safe to cancel.
async fn applied_version(conn: &mut PgConnection) -> Result<u64> {
    ensure_version_table(conn).await?;
    let (current, dirty) = read_version(conn).await?;
    if dirty {
        return Err(Error::DirtySchema { version: current });
    }
    Ok(current)
}

/// Applies the migrations above `current`, each under the dirty flag.
async fn apply(conn: &mut PgConnection, migrations: &[Migration], current: u64) -> Result<()> {
    for migration in migrations.iter().filter(|m| m.version > current) {
        tracing::info!(version = migration.version, "applying schema migration");
        set_version(conn, migration.version, true).await?;
        // The simple query protocol runs the whole file in one implicit
        // transaction, as the Go client does.
        sqlx::raw_sql(migration.sql)
            .execute(&mut *conn)
            .await
            .map_err(Error::Sqlx)?;
        set_version(conn, migration.version, false).await?;
    }
    Ok(())
}

/// Releases the lock and ends the session. Failures are only logged: ending
/// the session releases the lock anyway.
async fn finish(mut conn: PgConnection, lock: Option<i64>) {
    if let Some(lock) = lock
        && let Err(err) = sqlx::query("SELECT pg_advisory_unlock($1)")
            .bind(lock)
            .execute(&mut conn)
            .await
    {
        tracing::debug!(
            error = &err as &dyn std::error::Error,
            "migration unlock failed"
        );
    }
    if let Err(err) = conn.close().await {
        tracing::warn!(
            error = &err as &dyn std::error::Error,
            "closing the migration session failed"
        );
    }
}

/// golang-migrate's lock key for the version table: CRC-32 (IEEE) of
/// `"postgremq\0postgremq_migrations\0<database>"`, times its salt.
fn lock_id(database: &str) -> u32 {
    let key = format!("postgremq\0postgremq_migrations\0{database}");
    crc32(key.as_bytes()).wrapping_mul(LOCK_SALT)
}

fn crc32(data: &[u8]) -> u32 {
    !data.iter().fold(!0_u32, |crc, &byte| {
        (0..8).fold(crc ^ u32::from(byte), |c, _| {
            if c & 1 == 1 {
                0xedb8_8320 ^ (c >> 1)
            } else {
                c >> 1
            }
        })
    })
}

/// Creates the schema and version table if missing. Runs under the lock, and
/// checks first, so an installed database needs no `CREATE` privilege.
async fn ensure_version_table(conn: &mut PgConnection) -> Result<()> {
    let (schema_exists, table_exists): (bool, bool) = sqlx::query_as(
        "SELECT to_regnamespace('postgremq') IS NOT NULL, \
                to_regclass('postgremq.postgremq_migrations') IS NOT NULL",
    )
    .fetch_one(&mut *conn)
    .await
    .map_err(Error::Sqlx)?;
    if !schema_exists {
        sqlx::raw_sql("CREATE SCHEMA IF NOT EXISTS postgremq")
            .execute(&mut *conn)
            .await
            .map_err(Error::Sqlx)?;
    }
    if !table_exists {
        sqlx::raw_sql(
            "CREATE TABLE IF NOT EXISTS postgremq.postgremq_migrations \
             (version bigint not null primary key, dirty boolean not null)",
        )
        .execute(&mut *conn)
        .await
        .map_err(Error::Sqlx)?;
    }
    Ok(())
}

async fn read_version(conn: &mut PgConnection) -> Result<(u64, bool)> {
    let row: Option<(i64, bool)> =
        sqlx::query_as("SELECT version, dirty FROM postgremq.postgremq_migrations LIMIT 1")
            .fetch_optional(&mut *conn)
            .await
            .map_err(Error::Sqlx)?;
    let Some((version, dirty)) = row else {
        return Ok((0, false));
    };
    // golang-migrate records -1 (no version) after a failed first down
    // migration.
    Ok((u64::try_from(version).unwrap_or(0), dirty))
}

/// Replaces the version row atomically (one implicit transaction).
async fn set_version(conn: &mut PgConnection, version: u64, dirty: bool) -> Result<()> {
    sqlx::raw_sql(AssertSqlSafe(format!(
        "TRUNCATE postgremq.postgremq_migrations; \
         INSERT INTO postgremq.postgremq_migrations (version, dirty) VALUES ({version}, {dirty})"
    )))
    .execute(&mut *conn)
    .await
    .map_err(Error::Sqlx)?;
    Ok(())
}

#[cfg(test)]
#[path = "../tests/common/mod.rs"]
mod common;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lock_id_matches_golang_migrate() {
        // golang-migrate's database.GenerateAdvisoryLockId(db, "postgremq", "postgremq_migrations").
        assert_eq!(lock_id("postgres"), 2_735_559_060);
        assert_eq!(lock_id("mydb"), 1_257_508_284);
        assert_eq!(lock_id("pmq_ts_1"), 3_263_720_984);
    }

    #[test]
    fn embedded_migrations_are_those_of_the_pinned_schema_version() -> std::io::Result<()> {
        // Read the pin independently of build.rs, so a misparse there fails.
        let manifest = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("Cargo.toml"),
        )?;
        let pin: u64 = manifest
            .split("[package.metadata.postgremq]")
            .nth(1)
            .and_then(|table| table.split("mq-schema = ").nth(1))
            .and_then(|rest| rest.lines().next())
            .and_then(|value| value.trim().parse().ok())
            .unwrap_or_default();
        assert_eq!(MQ_SCHEMA, pin, "build.rs read the pin Cargo.toml declares");

        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("migrations");
        let mut files: Vec<String> = std::fs::read_dir(&dir)?
            .map(|entry| entry.map(|e| e.file_name().to_string_lossy().into_owned()))
            .collect::<std::io::Result<_>>()?;
        files.retain(|name| {
            name.ends_with(".up.sql")
                && name
                    .split('_')
                    .next()
                    .and_then(|n| n.parse::<u64>().ok())
                    .is_some_and(|n| n <= pin)
        });
        files.sort();
        assert_eq!(MIGRATIONS.len(), files.len(), "migrations 1..{pin}");
        for (file, migration) in files.iter().zip(MIGRATIONS) {
            assert!(
                file.starts_with(&format!("{:06}_", migration.version)),
                "{file} is embedded in order"
            );
            assert_eq!(std::fs::read_to_string(dir.join(file))?, migration.sql);
        }
        Ok(())
    }

    const BROKEN_SQL: &str =
        "CREATE TABLE postgremq.half_done (id int); SELECT * FROM no_such_table;";

    /// Migration 1, then a failing 2, then 3.
    const WITH_FAILURE: &[Migration] = &[
        Migration {
            version: 1,
            sql: MIGRATIONS[0].sql,
        },
        Migration {
            version: 2,
            sql: BROKEN_SQL,
        },
        Migration {
            version: 3,
            sql: "CREATE TABLE postgremq.after_broken (id int);",
        },
    ];

    /// Migration 1, then a working 2.
    const UPGRADE: &[Migration] = &[
        Migration {
            version: 1,
            sql: MIGRATIONS[0].sql,
        },
        Migration {
            version: 2,
            sql: "CREATE TABLE postgremq.upgraded (id int);",
        },
    ];

    async fn version_row(pool: &PgPool) -> (i64, bool) {
        sqlx::query_as("SELECT version, dirty FROM postgremq.postgremq_migrations")
            .fetch_one(pool)
            .await
            .unwrap_or_else(|err| unreachable!("{err}"))
    }

    async fn exists(pool: &PgPool, table: &str) -> bool {
        sqlx::query_scalar("SELECT to_regclass($1) IS NOT NULL")
            .bind(table)
            .fetch_one(pool)
            .await
            .unwrap_or_else(|err| unreachable!("{err}"))
    }

    #[tokio::test]
    async fn upgrades_an_installed_database_by_the_pending_migrations_only() -> Result<()> {
        let db = common::TestDb::empty().await;
        run(&db.pool, &UPGRADE[..1]).await?;
        assert_eq!(version_row(&db.pool).await, (1, false));

        run(&db.pool, UPGRADE).await?;

        assert_eq!(version_row(&db.pool).await, (2, false));
        assert!(exists(&db.pool, "postgremq.upgraded").await);
        Ok(())
    }

    #[tokio::test]
    async fn upgrades_a_latest_sql_install() -> Result<()> {
        let db = common::TestDb::new().await; // installs latest.sql
        let (installed, dirty) = version_row(&db.pool).await;
        assert!(!dirty && installed >= 1);
        // The installed migrations plus one more, as a later release adds.
        let next = u64::try_from(installed).unwrap_or_else(|err| unreachable!("{err}")) + 1;
        let mut upgrade: Vec<Migration> = MIGRATIONS
            .iter()
            .map(|m| Migration {
                version: m.version,
                sql: m.sql,
            })
            .collect();
        upgrade.push(Migration {
            version: next,
            sql: "CREATE TABLE postgremq.upgraded (id int);",
        });

        run(&db.pool, Box::leak(upgrade.into_boxed_slice())).await?;

        assert_eq!(version_row(&db.pool).await, (installed + 1, false));
        assert!(exists(&db.pool, "postgremq.upgraded").await);
        Ok(())
    }

    #[tokio::test]
    async fn a_failing_migration_leaves_its_version_dirty_and_stops() {
        let db = common::TestDb::empty().await;

        let err = run(&db.pool, WITH_FAILURE).await.err();

        assert!(
            matches!(&err, Some(Error::Sqlx(_))),
            "a failing migration is a database error: {err:?}"
        );
        assert_eq!(version_row(&db.pool).await, (2, true));
        assert!(
            !exists(&db.pool, "postgremq.half_done").await,
            "rolled back"
        );
        assert!(!exists(&db.pool, "postgremq.after_broken").await, "not run");
        let again = run(&db.pool, WITH_FAILURE).await.err();
        assert!(
            matches!(again, Some(Error::DirtySchema { version: 2, .. })),
            "{again:?}"
        );
    }

    #[tokio::test]
    async fn a_negative_version_row_reads_as_no_version() -> Result<()> {
        let db = common::TestDb::empty().await;
        migrate(&db.pool).await?;
        sqlx::query("UPDATE postgremq.postgremq_migrations SET version = -1, dirty = true")
            .execute(&db.pool)
            .await
            .map_err(Error::Sqlx)?;
        let status = migration_status(&db.pool).await?;
        assert_eq!((status.current_version, status.dirty), (0, true));
        let err = migrate(&db.pool).await.err();
        assert!(
            matches!(err, Some(Error::DirtySchema { version: 0, .. })),
            "{err:?}"
        );
        Ok(())
    }
}
