-- Down migrations are not supported for PostgreMQ
-- The schema should not be rolled back in production
--
-- If you need to remove the PostgreMQ schema, manually drop the tables and functions
-- or use a separate cleanup script
