version: 2

run:
  timeout: 5m
  tests: true

linters:
  # Use default linters but disable errcheck locally (too noisy in tests)
  # GitHub Actions will still catch important errors
  disable:
    - errcheck

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0
