version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # Use standard default linters
  default: standard
  disable:
    - errcheck  # Too noisy in tests

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0
